* Table of Contents
1. [[#about][About]]
2. [[#installation][Installation]]
3. [[#tutorial][Tutorial]]
4. [[#usage][Usage]]
5. [[#automatic-mesh-generation-algorithm][Automatic Mesh Generation Algorithm]]

* About
Pyems is a high-level, headless, and schema-driven Python interface to
the electromagnetic field solver, [[https://openems.de/start/index.php][OpenEMS]]. It uses OpenEMS's own
Python interface to hook into [[https://github.com/thliebig/CSXCAD][CSXCAD]] and [[https://github.com/thliebig/openEMS][OpenEMS]]. However, unlike
that interface, whose primary purpose is to expose the underlying C++
interface as a Python API, pyems provides high-level functionality
intended to facilitate and accelerate the simulation process.
Moreover, OpenEMS contains a number of subtle usage traps that can be
confusing to new users, and requires that those users understand
certain limitations of the FDTD algorithm. Pyems attempts (when
possible) to enforce correct usage in these situations and in other
cases to make the usage tradeoffs more visible.

Pyems focuses on being a robust translation and meshing engine. It is
designed to be easily integrated into automated design flows or driven
by external CAD tools via its declarative API. Recent updates landed
the formal JSON schema (v1), which ensures stability and
reproducibility across different driving environments.

To accomplish this goal, pyems provides:
1. Configurable, automatic mesh generation.
2. Simple port impedance and S-parameter calculations.
3. A collection of low-level port classes (Microstrip, Coax,
   Waveguide) designed for reliable EM excitation and measurement.
4. Functions performing frequently-needed calculations involved with
   microwave design.
5. Methods to optimize a simulation structure to achieve a desired
   result for any arbitrary parameter.
6. A JSON-based bridge (~pyems.runner~) for driving simulations from
   external environments.

* Installation
Pyems requires a working installation of OpenEMS, including its Python
interfaces for CSXCAD and OpenEMS. Pyems also requires the [[https://numpy.org/][NumPy]],
[[https://scipy.org/][SciPy]], and [[https://pypi.org/project/jsonschema/][jsonschema]] Python libraries.

To install pyems for development:
#+begin_src bash
cd pyems
pip install -e .
#+end_src

If you'd like to view simulation field dumps (recommended) you must also have a
copy of [[https://www.paraview.org/][ParaView]]. All of this software is (of course) open source and free to
download and use.

* Tutorial
The following tutorial describes how to simulate a simple microstrip line using
the pyems Python API. While pyems can also be driven via JSON, understanding the
Python API is helpful for understanding the underlying concepts.

#+begin_src python
import numpy as np
from pyems.simulation import Simulation
from pyems.mesh import Mesh
from pyems.port import MicrostripPort
from pyems.coordinate import Axis, Box3, Coordinate3

freq = np.linspace(0e9, 10e9, 101)
unit = 1e-3
sim = Simulation(freq=freq, unit=unit)
#+end_src

This first code block instantiates a ~Simulation()~
object. ~Simulation~ initializes the underlying OpenEMS objects for
the simulation structure and the FDTD algorithm. ~freq~ specifies the
frequency values to simulate. The post-simulation analysis results
(such as the S-parameters) will be given for these frequency
values. Bear in mind that using a smaller granularity results in a
longer simulation time. ~unit~ specifies the length unit to use in
meters. By using ~1e-3~, we've told pyems that all of our subsequent
dimensions will be given in mm.

#+begin_src python
# Define a microstrip port
port1_box = Box3(
    Coordinate3(-10, -1.5, 0),
    Coordinate3(10, 1.5, 0)
)

MicrostripPort(
    sim=sim,
    box=port1_box,
    propagation_axis=Axis("x", direction=1),
    excitation_axis=Axis("z", direction=1),
    number=1,
    thickness=0.035,
    excite=True,
    ref_impedance=50
)
#+end_src

~MicrostripPort~ is an example of an important concept in pyems: a port. Ports
are conceptually identical to the OpenEMS concept except that they integrate
better with the rest of pyems. A port is essentially a point of interface to the
outside world. Ports are locations where signal excitations are created and
where voltages and currents are measured.

#+begin_src python
Mesh(
    sim=sim,
    metal_res=1 / 40,
    nonmetal_res=1 / 10,
    expand_bounds=((8, 8), (8, 8), (8, 8)),
)
#+end_src

However, OpenEMS's FDTD algorithm needs to know where in that
structure it should be calculating the solutions to Maxwell's
equations at each timestep. This is where the simulation mesh comes in
and is, in my opinion, one of the greatest advantages of pyems over
OpenEMS's default Python interface. Traditionally, creating the mesh
has been one of the hardest and most cumbersome parts of the OpenEMS
simulation process. There are a number of implementation-specific
reasons for this. For instance, the FDTD algorithm performs badly when
a mesh line is placed at the boundary of a conductor and
insulator. Instead, something called the [[https://openems.de/index.php/FDTD_Mesh.html][thirds rule]] should be applied
to achieve a more accurate simulation result without simply adding
more mesh lines (which would increase the simulation time). Pyems
takes care of this and a bunch of other implementation-specific
details for you.

#+begin_src python
sim.run()
#+end_src

* Usage
** Headless Runner (JSON)
Pyems provides a formal, versioned JSON interface for driving simulations
without writing Python code. This is particularly useful for integrating pyems
into other software environments, such as the FreeCAD EMS workbench.

The runner validates input files against a strict schema (v1.0) before
execution, ensuring that physical constraints and data types are correct.

#+begin_src bash
python -m pyems.runner simulation.json
#+end_src

The schema definition and documentation can be found in the ~schema/~
directory. A ~--validate-only~ flag is available for pre-simulation checks:

#+begin_src bash
python -m pyems.runner --validate-only simulation.json
#+end_src

** Automatic Mesh Generation Algorithm
This section describes how the automatic mesh generation algorithm
works.

In order to generate a mesh from a CSXCAD geometry, pyems starts by
getting a list of all physical CSXCAD primitives (i.e., CSXCAD
primitives that have an effect on the simulation). Then, for each
dimension it extracts a list of locations for mesh lines that must be
fixed at those locations. These correspond to zero-dimension
structures (e.g., a planar structure created by
~AddConducting_sheet~). Next, pyems iterates through the full list of
physical primitives and extracts 3 lists of boundary positions, one
for each dimension. For example, a boundary position in the
x-dimension would correspond to a location where the physical
properties of the structure change anywhere at that location. This
change could occur in the y-dimension or the z-dimension. Boundary
positions in the y-dimension and z-dimension lists are analogous.

Pyems then converts each element of these lists of boundary positions
in each dimension to a type that associates a boundary region
(consisting of lower and upper bounds) with a CSXCAD property type,
which it classifies as metal, nonmetal or air. This is called a
~BoundedType~. To associate the property type it finds the type of the
primitive corresponding to the smallest length in that dimension
encompassing the bounded region. Where ties exist, the metal type gets
priority.

Pyems then adds peripheral ~BoundedType~'s for simulation air space,
records the location of boundaries between a metal, and nonmetal and
orders the ~BoundedType~'s by size (smallest first). Then, it iterates
through this list of ~BoundedType~'s and generates a list of mesh line
locations inside each.

Generating this list of mesh lines in each ~BoundedType~ is, of
course, where most of the work happens. Pyems starts by finding the
mesh line spacing at the lower and upper boundaries of the boundary
region. It also determines the maximum spacing in this region
according to ~metal_res~ and ~nonmetal_res~ specified by the user and
whether this ~BoundedType~ is a metal or not. Then it adjusts the
upper and lower line positions if they correspond to metal-nonmetal
boundaries, which must satisfy the thirds rule. For instance, if the
upper boundary position corresponds to a metal-nonmetal boundary, we
would move the upper position 1/3 the mesh spacing inside the
boundary. Then pyems computes a geometric series whose constant factor
is between 1 and the smoothness factor specified by the user for that
dimension and whose distance is equal to the distance of the bounded
region. Computing the geometric series uses a Scipy optimization
routine and accounts for most of the time spent generating the mesh.

Finally, pyems trims the air mesh to the desired number of cells,
smooths the mesh so that the mesh spacing inside the PML is uniform,
calls hooks to other parts of pyems that need to know the final mesh
location (e.g., probes need to align to the mesh), and generates the
actual mesh in the CSXCAD structure. It then performs a number of
checks for correctness.

* Textbook References
1. **Pozar** refers to "Microwave Engineering" by David Pozar, Fourth Edition.
2. **Wadell** refers to "Transmission Line Design Handbook" by Brian Wadell, 1991.

* To-Do
** TODO via wall should support nonzero dimensions
The via wall otherwise often gets ignored. I believe this is a result
of the floating point precision errors.

** TODO probe should not hold onto freq
** TODO probe get_freq_data and get_time_data
These methods are poorly named. freq_data and time_data are better
names. Additionally, they shouldn't pass back frequency and time
values. This should be retreived with other methods. Note that this
will require adjustments to port.py too.

** TODO rectwaveguideport propagation axis
This should use the Axis object.

** TODO port calc requires self._propagation_axis set
self._propagation_axis is not currently required for the port base
class. The interface must be changed in some way that is also
compatible with the derived classes.

** HOLD mesh should support primitive priorities
